### ISSUE TITLE
Wrap dos links importantes

### ISSUE THREAD

**Issue by VytorCalixto** [PETComputacaoUFPR/petcomputacaoufpr.github.io#5]
Dependendo da resolução da tela o wrap dos links "quebra", deixando um texto sobre o outro. Segue imagem:
![captura de tela de 2015-06-01 11 29 40](https://cloud.githubusercontent.com/assets/7662987/7915097/a7daf100-0851-11e5-894e-68e81f646852.png)

**Comment by jomaro** [comment]
ta
